== APP - api == Traceback (most recent call last):
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/bin/uvicorn", line 10, in <module>
== APP - api ==     sys.exit(main())
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/click/core.py", line 1442, in __call__
== APP - api ==     return self.main(*args, **kwargs)
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/click/core.py", line 1363, in main
== APP - api ==     rv = self.invoke(ctx)
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/click/core.py", line 1226, in invoke
== APP - api ==     return ctx.invoke(self.callback, **ctx.params)
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/click/core.py", line 794, in invoke
== APP - api ==     return callback(*args, **kwargs)
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 413, in main
== APP - api ==     run(
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 580, in run
== APP - api ==     server.run()
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 67, in run
== APP - api ==     return asyncio.run(self.serve(sockets=sockets))
== APP - api ==   File "/home/reinan/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/asyncio/runners.py", line 44, in run
== APP - api ==     return loop.run_until_complete(main)
== APP - api ==   File "/home/reinan/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
== APP - api ==     return future.result()
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 71, in serve
== APP - api ==     await self._serve(sockets)
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 78, in _serve
== APP - api ==     config.load()
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 436, in load
== APP - api ==     self.loaded_app = import_from_string(self.app)
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 22, in import_from_string
== APP - api ==     raise exc from None
== APP - api ==   File "/home/reinan/dev/scheduled-messages/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
== APP - api ==     module = importlib.import_module(module_str)
== APP - api ==   File "/home/reinan/.local/share/uv/python/cpython-3.10.17-linux-x86_64-gnu/lib/python3.10/importlib/__init__.py", line 126, in import_module
== APP - api ==     return _bootstrap._gcd_import(name[level:], package, level)
== APP - api ==   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
== APP - api ==   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
== APP - api ==   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
== APP - api ==   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
== APP - api ==   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
== APP - api ==   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
== APP - api ==   File "/home/reinan/dev/scheduled-messages/api/app.py", line 2, in <module>
== APP - api ==     from api.messages import router
== APP - api == ModuleNotFoundError: No module named 'api'
The App process exited with error code: exit status 1

termination signal received: shutting down
Error exiting App: exit status 1
